<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Model\BattleSystem\Bot\" />
	  <Folder Include="Model\BattleSystem\Player\" />
	  <Folder Include="Model\Helper\MoveHelper\" />
	  <Folder Include="Model\Map\" />
	</ItemGroup>

</Project>
