<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Model\BattleSystem\**" />
	  <Compile Remove="Model\Map\**" />
	  <EmbeddedResource Remove="Model\BattleSystem\**" />
	  <EmbeddedResource Remove="Model\Map\**" />
	  <None Remove="Model\BattleSystem\**" />
	  <None Remove="Model\Map\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Data.OleDb" Version="10.0.5" />
	</ItemGroup>

</Project>
