<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- 7.0.14 is the last version that supports netstandard2.0 -->
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.14" />

		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.0" />	
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Data.OleDb" Version="7.0.0" />
		<PackageReference Include="System.Text.Json" Version="7.0.4" />
		<PackageReference Include="System.IO.Pipelines" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="PresentationCore">
			<HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\PresentationCore.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>