using System;
using System.Collections.Generic;
using System.Text;

namespace PokemonGame.Services.Enums.PokemonEnum
{
    public enum FormType: byte
    {
        Arceus = 0,
        Arceus_Bug = 6,
        Arceus_Dark = 16,
        Arceus_Dragon = 15,
        Arceus_Electric = 12,
        Arceus_Fighting = 1,
        Arceus_Fire = 9,
        Arceus_Flying = 2,
        Arceus_Ghost = 7,
        Arceus_Grass = 11,
        Arceus_Ground = 4,
        Arceus_Ice = 14,
        Arceus_Poison = 3,
        Arceus_Psychic = 13,
        Arceus_Rock = 5,
        Arceus_Steel = 8,
        Arceus_Water = 10,
        Basculin_Blue = 1,
        Basculin_Red = 0,
        Burmy_Plant = 0,
        Burmy_Sandy = 1,
        Burmy_Trash = 2,
        Castform = 0,
        Castform_Rainy = 2,
        Castform_Snowy = 3,
        Castform_Sunny = 1,
        Cherrim = 0,
        Cherrim_Sunshine = 1,
        Darmanitan = 0,
        Darmanitan_Zen = 1,
        Deerling_Autumn = 2,
        Deerling_Spring = 0,
        Deerling_Summer = 1,
        Deerling_Winter = 3,
        Deoxys = 0,
        Deoxys_Attack = 1,
        Deoxys_Defense = 2,
        Deoxys_Speed = 3,
        Gastrodon_East = 1,
        Gastrodon_West = 0,
        Genesect = 0,
        Genesect_Burn = 3,
        Genesect_Chill = 4,
        Genesect_Douse = 1,
        Genesect_Shock = 2,
        Giratina = 0,
        Giratina_Origin = 1,
        Keldeo = 0,
        Keldeo_Resolute = 1,
        Kyurem = 0,
        Kyurem_Black = 2,
        Kyurem_White = 1,
        Landorus = 0,
        Landorus_Therian = 1,
        Meloetta = 0,
        Meloetta_Pirouette = 1,
        Rotom = 0,
        Rotom_Fan = 4,
        Rotom_Frost = 3,
        Rotom_Heat = 1,
        Rotom_Mow = 5,
        Rotom_Wash = 2,
        Sawsbuck_Autumn = 2,
        Sawsbuck_Spring = 0,
        Sawsbuck_Summer = 1,
        Sawsbuck_Winter = 3,
        Shaymin = 0,
        Shaymin_Sky = 1,
        Shellos_East = 1,
        Shellos_West = 0,
        Thundurus = 0,
        Thundurus_Therian = 1,
        Tornadus = 0,
        Tornadus_Therian = 1,
        Unown_A = 0,
        Unown_B = 1,
        Unown_C = 2,
        Unown_D = 3,
        Unown_E = 4,
        Unown_Exclamation = 26,
        Unown_F = 5,
        Unown_G = 6,
        Unown_H = 7,
        Unown_I = 8,
        Unown_J = 9,
        Unown_K = 10,
        Unown_L = 11,
        Unown_M = 12,
        Unown_N = 13,
        Unown_O = 14,
        Unown_P = 15,
        Unown_Q = 16,
        Unown_Question = 27,
        Unown_R = 17,
        Unown_S = 18,
        Unown_T = 19,
        Unown_U = 20,
        Unown_V = 21,
        Unown_W = 22,
        Unown_X = 23,
        Unown_Y = 24,
        Unown_Z = 25,
        Wormadam_Plant = 0,
        Wormadam_Sandy = 1,
        Wormadam_Trash = 2
        #pragma warning restore CA1069 // Enums values should not be duplicated
    }
}
