name: Auto Fix C# Style

on:
  pull_request:
  
jobs:
  format:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # use PAT here
          fetch-depth: 0         # fetch full history
          ref: ${{ github.head_ref }}  # checkout the PR branch

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Fix formatting
        run: dotnet format

      - name: Commit fixes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto fix code style"
          git push origin HEAD  # push to the current PR branch
