name: Style Check

on:
  pull_request:

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Run style check
        run: dotnet format --verify-no-changes
